from __future__ import annotations

from app.models.schemas import ArchitectureStyle


def load_default_styles() -> list[ArchitectureStyle]:
    return [ArchitectureStyle(**item) for item in DEFAULT_STYLES]


DEFAULT_STYLES = [
    {
        "id": "layered",
        "name": "分层架构",
        "category": "mainstream",
        "description": "按表现层、业务层、数据访问层等职责分层，适合业务规则清晰的管理系统。",
        "suitable_for": ["企业后台", "信息管理系统", "中小型 Web 应用"],
        "quality_scores": {"scalability": 0.55, "performance": 0.58, "reliability": 0.66, "modifiability": 0.72, "complexity": 0.82, "realtime": 0.35},
        "strengths": ["结构清晰", "开发门槛低", "便于团队分工", "测试和维护成本较低"],
        "weaknesses": ["横向扩展能力有限", "层间调用链可能变长", "不适合强实时事件流场景"],
        "topology": "flowchart LR\n  UI[表现层] --> Service[业务层]\n  Service --> Repo[数据访问层]\n  Repo --> DB[(数据库)]",
        "rules": {"prefer": ["管理", "后台", "CRUD", "表单", "权限"], "avoid": ["万人", "实时", "流式", "高频事件"]},
    },
    {
        "id": "microservices",
        "name": "微服务架构",
        "category": "mainstream",
        "description": "把系统拆分为围绕业务能力的独立服务，通过 API 网关和服务通信协同。",
        "suitable_for": ["复杂业务平台", "快速迭代产品", "多团队协作", "弹性伸缩系统"],
        "quality_scores": {"scalability": 0.9, "performance": 0.68, "reliability": 0.74, "modifiability": 0.86, "complexity": 0.38, "realtime": 0.58},
        "strengths": ["服务独立部署", "扩展性强", "便于技术异构", "故障隔离能力较好"],
        "weaknesses": ["分布式治理复杂", "链路追踪和运维要求高", "数据一致性设计成本高"],
        "topology": "flowchart LR\n  Client[客户端] --> Gateway[API Gateway]\n  Gateway --> User[用户服务]\n  Gateway --> Order[业务服务]\n  Gateway --> Media[扩展服务]\n  User --> DB1[(用户库)]\n  Order --> DB2[(业务库)]",
        "rules": {"prefer": ["扩展", "多团队", "独立部署", "复杂业务", "弹性", "云原生"], "avoid": ["简单", "单体", "课程小练习"]},
    },
    {
        "id": "event_driven",
        "name": "事件驱动架构",
        "category": "mainstream",
        "description": "以事件生产、事件总线和消费者为核心，适合异步解耦、高并发和实时通知场景。",
        "suitable_for": ["即时通信", "交易通知", "IoT 事件流", "高并发异步处理"],
        "quality_scores": {"scalability": 0.88, "performance": 0.82, "reliability": 0.76, "modifiability": 0.8, "complexity": 0.45, "realtime": 0.86},
        "strengths": ["高吞吐量", "模块解耦", "便于异步削峰", "适合实时消息与通知"],
        "weaknesses": ["事件一致性难度高", "调试和链路追踪复杂", "事件模型需要规范治理"],
        "topology": "flowchart LR\n  Producer[事件生产者] --> Bus[(事件总线)]\n  Bus --> C1[消息消费者]\n  Bus --> C2[通知消费者]\n  Bus --> C3[分析消费者]\n  C1 --> Store[(事件/消息存储)]",
        "rules": {"prefer": ["实时", "消息", "事件", "异步", "高并发", "通知", "削峰", "IoT"], "avoid": ["强事务", "同步审批"]},
    },
    {
        "id": "monolithic",
        "name": "单体架构",
        "category": "baseline",
        "description": "所有模块打包部署为一个应用，适合范围明确、团队较小、上线速度优先的系统。",
        "suitable_for": ["MVP", "小型管理系统", "课程原型"],
        "quality_scores": {"scalability": 0.35, "performance": 0.62, "reliability": 0.58, "modifiability": 0.45, "complexity": 0.9, "realtime": 0.32},
        "strengths": ["实现简单", "部署直接", "本地调试方便", "初期开发速度快"],
        "weaknesses": ["规模变大后维护困难", "独立扩展能力弱", "技术栈演进成本高"],
        "topology": "flowchart LR\n  Client[客户端] --> App[单体应用]\n  App --> DB[(数据库)]",
        "rules": {"prefer": ["MVP", "简单", "原型", "小型", "单团队"], "avoid": ["万人", "快速扩展", "复杂业务", "高可用"]},
    },
    {
        "id": "hexagonal",
        "name": "六边形架构",
        "category": "domain-centric",
        "description": "将领域核心与外部适配器隔离，适合长期演进、测试要求高的业务系统。",
        "suitable_for": ["领域模型复杂系统", "金融业务", "需要多端适配的系统"],
        "quality_scores": {"scalability": 0.62, "performance": 0.6, "reliability": 0.75, "modifiability": 0.88, "complexity": 0.5, "realtime": 0.42},
        "strengths": ["核心业务独立", "可测试性强", "外部依赖可替换", "适合领域驱动设计"],
        "weaknesses": ["抽象层较多", "初期设计成本高", "对团队建模能力有要求"],
        "topology": "flowchart LR\n  Web[Web 适配器] --> Port[输入端口]\n  Port --> Domain[领域核心]\n  Domain --> OutPort[输出端口]\n  OutPort --> DB[(数据库适配器)]\n  OutPort --> MQ[消息适配器]",
        "rules": {"prefer": ["领域", "长期演进", "测试", "多端", "业务规则"], "avoid": ["极简", "一次性脚本"]},
    },
    {
        "id": "clean",
        "name": "整洁架构",
        "category": "domain-centric",
        "description": "强调依赖规则向内，实体和用例不依赖框架，适合复杂业务和长期维护。",
        "suitable_for": ["企业核心系统", "强业务规则系统", "可维护性优先系统"],
        "quality_scores": {"scalability": 0.64, "performance": 0.57, "reliability": 0.74, "modifiability": 0.9, "complexity": 0.46, "realtime": 0.38},
        "strengths": ["框架无关", "业务规则稳定", "测试友好", "便于替换外部设施"],
        "weaknesses": ["模板代码较多", "学习成本较高", "小项目可能显得过重"],
        "topology": "flowchart TD\n  UI[接口层] --> UseCase[用例层]\n  UseCase --> Entity[实体层]\n  Infra[基础设施] --> UseCase",
        "rules": {"prefer": ["核心业务", "长期维护", "框架无关", "用例", "实体"], "avoid": ["简单 CRUD", "短期原型"]},
    },
    {
        "id": "serverless",
        "name": "Serverless 架构",
        "category": "cloud",
        "description": "以函数计算和托管服务为中心，适合事件触发、弹性波动明显、运维投入低的场景。",
        "suitable_for": ["突发流量", "事件触发任务", "轻运维应用", "自动化处理"],
        "quality_scores": {"scalability": 0.86, "performance": 0.6, "reliability": 0.7, "modifiability": 0.68, "complexity": 0.58, "realtime": 0.5},
        "strengths": ["按需伸缩", "运维成本低", "适合事件触发", "上线速度快"],
        "weaknesses": ["冷启动风险", "供应商绑定", "本地调试和可观测性较复杂"],
        "topology": "flowchart LR\n  Trigger[HTTP/事件触发] --> Function[云函数]\n  Function --> Managed[(托管数据库/对象存储)]\n  Function --> Queue[(托管队列)]",
        "rules": {"prefer": ["突发", "函数", "低运维", "自动扩缩", "事件触发"], "avoid": ["低延迟", "长连接", "状态会话"]},
    },
    {
        "id": "pipe_filter",
        "name": "管道-过滤器架构",
        "category": "dataflow",
        "description": "将数据处理拆为可组合过滤器，适合 ETL、编译器、数据清洗和流水线处理。",
        "suitable_for": ["数据处理", "ETL", "日志分析", "批处理流水线"],
        "quality_scores": {"scalability": 0.7, "performance": 0.72, "reliability": 0.62, "modifiability": 0.78, "complexity": 0.65, "realtime": 0.48},
        "strengths": ["处理步骤清晰", "组件可复用", "易于并行化", "适合数据流编排"],
        "weaknesses": ["全局错误处理复杂", "不适合强交互业务", "中间数据格式需统一"],
        "topology": "flowchart LR\n  Source[数据源] --> F1[清洗过滤器]\n  F1 --> F2[转换过滤器]\n  F2 --> F3[分析过滤器]\n  F3 --> Sink[输出]",
        "rules": {"prefer": ["数据流", "ETL", "清洗", "流水线", "批处理", "日志"], "avoid": ["复杂交互", "强事务"]},
    },
    {
        "id": "cqrs",
        "name": "CQRS 架构",
        "category": "data-consistency",
        "description": "读写模型分离，适合读写压力差异大、审计和事件溯源要求明显的系统。",
        "suitable_for": ["高读写压力系统", "订单交易", "审计系统", "复杂查询平台"],
        "quality_scores": {"scalability": 0.82, "performance": 0.78, "reliability": 0.7, "modifiability": 0.68, "complexity": 0.36, "realtime": 0.62},
        "strengths": ["读写独立优化", "适合复杂查询", "可结合事件溯源", "提升高读场景性能"],
        "weaknesses": ["最终一致性复杂", "模型同步成本高", "开发和测试成本较高"],
        "topology": "flowchart LR\n  Client[客户端] --> Command[命令模型]\n  Client --> Query[查询模型]\n  Command --> EventStore[(事件存储)]\n  EventStore --> Projector[投影器]\n  Projector --> ReadDB[(读库)]",
        "rules": {"prefer": ["读多写少", "审计", "事件溯源", "复杂查询", "订单"], "avoid": ["简单 CRUD", "小型系统"]},
    },
    {
        "id": "soa",
        "name": "SOA 架构",
        "category": "enterprise",
        "description": "以企业级服务契约和集成为核心，适合跨系统复用和遗留系统整合。",
        "suitable_for": ["企业集成", "遗留系统改造", "跨部门服务复用"],
        "quality_scores": {"scalability": 0.66, "performance": 0.58, "reliability": 0.72, "modifiability": 0.7, "complexity": 0.42, "realtime": 0.36},
        "strengths": ["服务复用", "契约治理", "适合企业集成", "兼容遗留系统"],
        "weaknesses": ["治理成本高", "ESB 可能成为瓶颈", "敏捷迭代速度一般"],
        "topology": "flowchart LR\n  AppA[系统 A] --> ESB[企业服务总线]\n  AppB[系统 B] --> ESB\n  ESB --> S1[客户服务]\n  ESB --> S2[支付服务]\n  ESB --> Legacy[遗留系统]",
        "rules": {"prefer": ["企业集成", "遗留", "跨部门", "服务复用", "ESB"], "avoid": ["创业 MVP", "低延迟实时"]},
    },
    {
        "id": "blackboard",
        "name": "黑板架构",
        "category": "ai",
        "description": "多个知识源围绕共享黑板协作，适合 AI 推理、诊断和复杂问题求解。",
        "suitable_for": ["AI 诊断", "专家系统", "多智能体推理", "复杂识别任务"],
        "quality_scores": {"scalability": 0.52, "performance": 0.45, "reliability": 0.62, "modifiability": 0.76, "complexity": 0.34, "realtime": 0.3},
        "strengths": ["便于多知识源协同", "适合渐进式推理", "支持不确定性问题求解"],
        "weaknesses": ["控制策略复杂", "性能瓶颈明显", "知识源冲突处理困难"],
        "topology": "flowchart LR\n  KS1[知识源 A] --> Board[(共享黑板)]\n  KS2[知识源 B] --> Board\n  KS3[知识源 C] --> Board\n  Controller[控制器] --> Board",
        "rules": {"prefer": ["AI", "诊断", "专家系统", "多智能体", "推理"], "avoid": ["高吞吐交易"]},
    },
    {
        "id": "mvc",
        "name": "MVC 架构",
        "category": "presentation",
        "description": "将模型、视图、控制器分离，适合交互式 Web 或桌面应用的表现层组织。",
        "suitable_for": ["Web 应用", "后台界面", "表单系统", "内容管理"],
        "quality_scores": {"scalability": 0.5, "performance": 0.56, "reliability": 0.6, "modifiability": 0.7, "complexity": 0.78, "realtime": 0.32},
        "strengths": ["界面与业务分离", "成熟框架支持", "适合快速开发 Web 页面"],
        "weaknesses": ["复杂业务中模型易膨胀", "不解决分布式扩展问题", "实时能力一般"],
        "topology": "flowchart LR\n  User[用户] --> Controller[Controller]\n  Controller --> Model[Model]\n  Model --> View[View]\n  View --> User",
        "rules": {"prefer": ["Web", "页面", "表单", "后台", "内容"], "avoid": ["高并发实时", "复杂分布式"]},
    },
]
